# Generated by Django 4.2 on 2023-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='harga',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='harga_diskon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('furniture', 'furniture'), ('electronics', 'electronics'), ('fashion', 'fashion')], max_length=100),
        ),
    ]
